agent_name: welsh-founder-hunter
runtime: python3.11
dependencies:
  - requests>=2.31.0
  - networkx>=3.1
  - pandas>=2.0.0
  - python-dateutil>=2.8.0
  - pyyaml>=6.0
  - jinja2>=3.1.0
  - weasyprint>=60.0
  - discord.py>=2.3.0
  - stacks-blockchain-api>=2.0.0
secrets:
  HIRO_API_KEY: ${{ env.HIRO_API_KEY }}
  DISCORD_BOT_TOKEN: ${{ env.DISCORD_BOT_TOKEN }}
  GITHUB_PAT: ${{ env.GITHUB_PAT }}
  AWS_ACCESS_KEY_ID: ${{ env.AWS_ACCESS_KEY_ID }}
  AWS_SECRET_ACCESS_KEY: ${{ env.AWS_SECRET_ACCESS_KEY }}
workflow:
  entrypoint: bootstrap
resources:
  memory: 2Gi
  cpu: 1000m
  timeout: 3600s